New compile script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,35 +1,75 @@
-#!/usr/bin/env bash
-# bin/compile <build-dir> <cache-dir> <env-dir>
+#!/bin/bash
 
-set -e
+# Heroku standard way to log buildpack info to console
+status() {
+  echo "-----> $*"
+}
+
+set -e          # fail fast
+set -o pipefail # don't ignore exit codes when piping output
 
 build_dir=$1
 cache_dir=$2
 env_dir=$3
-bp_dir=$(dirname $(dirname $0))
 
-# fetch_nginx_tarball() {
-#     local version="1.9.7"
-#     local tarball_file="nginx-$version.tgz"
-#     local stack="heroku-18"
-#     # local nginx_tarball_url="https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/nginx/$stack/nginx-$version-ngx_mruby.tgz"
-#     local nginx_url="https://github.com/heroku/heroku-buildpack-nginx/blob/master/bin/nginx-heroku-18?raw=true"
-#     local dest_path="$cache_dir/$stack/$tarball_file"
+# Versions
+NGINX_VERSION=1.11.3
+MRUBY_VERSION=v1.18.3
 
-#     if [ -f "$dest_path" ]; then
-#         echo -n "cat $dest_path"
-#     else
-#         # echo -n "curl -L $nginx_tarball_url"
-#         curl -o -L $nginx_url
-#     fi
-# }
+# Download URLs
+nginx_tarball_url=http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
+mruby_github_url=https://github.com/matsumoto-r/ngx_mruby
 
-mkdir -p $build_dir/bin
-curl -o $build_dir/bin/nginx -L "https://github.com/heroku/heroku-buildpack-nginx/blob/master/bin/nginx-heroku-18?raw=true"
+# Build paths
+cache=$cache_dir/build/nginx-with-mruby/${NGINX_VERSION}-mruby-${MRUBY_VERSION}
+build=${BUILD_PREFIX}/app/nginx
+src=${PWD}/nginx-${NGINX_VERSION}
+mruby_src=${PWD}/ngx_mruby
 
-nginx_version=$($build_dir/bin/nginx -V 2>&1 | head -1 | awk '{ print $NF }')
-cp -a $bp_dir/scripts/{boot,config} -t $build_dir/bin/
-echo "-----> Installed ${nginx_version} to /app/bin"
+mkdir -p $build
+
+if [ -e $cache ]; then
+# Use cached nginx
+  status "Using previously compiled nginx-$NGINX_VERSION"
+  cp -R $cache/nginx/* $build
+else
+  status "Downloading $nginx_tarball_url"
+  curl -L $nginx_tarball_url | tar xz
+
+  status "Downloading MRuby ${MRUBY_VERSION}"
+  if [ -d "$mruby_src" ]; then
+    rm -rf ${mruby_src}
+  fi
+
+  git clone $mruby_github_url
+  pushd ${mruby_src}
+  git checkout $MRUBY_VERSION
+  popd
+
+  status "Compiling MRuby"
+  cp ./mruby_build_config.rb $mruby_src/build_config.rb
+  pushd ${mruby_src}
+  ./configure --with-ngx-src-root=${src}
+  make build_mruby
+  popd
+
+  status "Compiling nginx"
+  pushd $src
+  ./configure --prefix=$build --with-ipv6 --with-http_stub_status_module --with-http_realip_module --with-http_ssl_module --add-module=${mruby_src} --add-module=${mruby_src}/dependence/ngx_devel_kit $NGINX_OPTIONS
+  make install --silent
+
+  # Clear out cache if our version doesn't exist
+  status "Caching build"
+  rm -rf $cache_dir/*
+  mkdir -p $cache
+  cp -R $build $cache
+fi
+
+mv $build $build_dir
+
+# Add to PATH
+mkdir -p $build_dir/.profile.d
+echo 'PATH=$PATH:$HOME/nginx/sbin' > $build_dir/.profile.d/nginx_path.sh
 
 mkdir -p $build_dir/config
 cp $bp_dir/scripts/config/templates/mime.types $build_dir/config
